defmodule Microscope.IndexBuilder.Payload do
  @moduledoc false

  require EEx

  @version Mix.Project.config()[:version]

  @stylesheet """
  th,td{padding:2px 5px}
  th{text-align:left;background:white}
  td{font-family:monospace;font-size:10pt}
  tr:nth-of-type(2n){background:#eee}
  tr:nth-of-type(2n+1){background:#ddd}
  tr td:last-child{text-align:right}
  """

  @page_template """
  <!doctype html><html><head><meta charset="utf-8">
  <title>Index of <%=url%></title><style>#{@stylesheet}</style></head><body>
  <h1>Index of <%=url%></h1>
  <table><tr><th>Name</th><th>Last Modified</th><th>Size</th></tr><tr>
  <td><a href="..">Parent Directory</a></td><td></td><td>(directory)</td>
  </tr><%= for {type, name, mtime, size} <- files do %><tr><td>
  <a href="<%=url<>name%>"><%=name%><%=if type == :directory, do: "/"%></a>
  </td><td><%=mtime%></td><td>
  <%= if type == :directory do %>(directory)<% else %><%=size%> bytes<% end %>
  </td></tr><% end %></table><hr>Generated by Microscope v#{@version}
  <a href="https://github.com/Dalgona/microscope">
  https://github.com/Dalgona/microscope</a></body></html>
  """

  EEx.function_from_string(:def, :page_template, @page_template, [:url, :files])
end
